#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

hora=`date +%H`

if [ $hora -le 17  ] && [ $hora -ge 07 ] 
then
	# this config is for ligth theme
  feh --bg-fill ~/Pictures/Wallpaper/bigsurL.jpg
else
	# this config is for dark theme
  feh --bg-fill ~/Pictures/Wallpaper/bigsurD.jpg
fi


~/.config/polybar/./launch.sh
picom --experimental-backends &
bspc config border_width 0
xsetroot -cursor_name left_ptr &
